export const SET_ISLOGIN = 'SET_ISLOGIN'

export const SET_USERDATA = 'SET_USERDATA'

export const SET_TEMPORARY_REQUEST = 'SET_TEMPORARY_REQUEST'

export const SET_HANDLE_REQUEST = 'SET_HANDLE_REQUEST'
