export const SET_ISLOGIN = 'SET_ISLOGIN'

export const SET_USERDATA = 'SET_USERDATA'

export const SET_TEMPORARY_REQUEST = 'SET_TEMPORARY_REQUEST'

export const SET_HANDLE_REQUEST = 'SET_HANDLE_REQUEST'

export const SET_TEMPORARY_WARNING= 'SET_TEMPORARY_WARNING'

export const SET_HANDLE_WARNING = 'SET_HANDLE_WARNING'

export const SET_SERVICE_NUMBER= 'SET_SERVICE_NUMBER'

export const SET_FAULTS_NUMBER= 'SET_FAULTS_NUMBER'

